### ISSUE TITLE
Kontrola

### ISSUE THREAD

**Issue by Hedwika** [Hedwika/python-012021#1]
Ahoj @pesikj ,

prosím o kontrolu domácích úkolů. Vše je otestované a neměla jsem problém, pouze u příkladu 5: máme v zadání v seznamu prodejů z roku 2020 dvakrát knihu s názvem "Zkus mě chytit". Považuji to za chybku v zadání, předpokládala bych, že data budou bez duplicit. Dej mi prosím vědět, zda je to schválně a je potřeba slovník upravit a položky sečíst, nebo je to omyl.

Děkuji a přeji krásný víkend
Hedvika

**Comment by pesikj** [comment]
Ahoj Hedviko,

super :-)

### 1. úkol :heavy_check_mark:

Správně, pouze by se dala zjednodušit podmínka. Pokud je hodnota ve slovníku sama o sobě `True`, není potřeba to s `True` porovnávat. Stačilo by to, jak je to níže :-)
​
```python
    if baliky[kod]:
        print("Balík byl předán kurýrovi.")
```
​
### 2. úkol :heavy_check_mark:

​Ideální :-)
​
### 3. úkol :heavy_check_mark:

Tady ses to snažila mít jazykově vymazlené, Teoreticky by se mohlo stát, že bude volný jeden meeting room, pak bys mohla podmínku upravit třeba takto: 

```python
    if len(volnePokoje[cas]) in (0, 1):
        print("K dispozici je " + str(len(volnePokoje[cas])) + " meeting room.")
    else:
        print("K dispozici jsou " + str(len(volnePokoje[cas])) + " meeting rooms.")
```

### 4. úkol :heavy_check_mark:
​Super
​
### 5. úkol :heavy_check_mark:

Tady máš podmínky správně, ale zápis je trochu složitý. Šlo by to napsat i tak, že si vytvoříš proměnnou (např. `prodejeVybraneKnihy`), na začátku jí nastavit 0 a pak pro oba slovníky provést kontrolu a přičtení. Může to vypadat jako v kódu níže :-)

```python
if nazev in prodeje2019:
    prodejeKnihy = prodejeKnihy + prodeje2019[nazev]
if nazev in prodeje2020:
    prodejeKnihy = prodejeKnihy + prodeje2020[nazev]
if prodejeKnihy == 0:
    print("Kniha není v seznamu.")
else:
    print(f"Knihy se prodalo {prodejeKnihy} ks.")
```
​
Shrnutí:

Zpsal jsem ti 5 bodů :-) Skvělá práce, jen tak dál 👍

**Comment by Hedwika** [comment]
Ahoj Jirko,

moc děkuji za super rychlou kontrolu a sdílení vychytávek na lepší kód - chápu vše a přijde mi to super :)

Děkuji a přeji krásný víkend
Hedvika
