### ISSUE TITLE
Hedvika - úkoly z desáté lekce

### ISSUE THREAD

**Issue by Hedwika** [Hedwika/python-012021#10]
Ahoj Jirko,

právě jsem nahrála úkoly z desáté lekce, ale pushla jsem je omylem jako úkoly z 11. lekce. :)

Vše bylo ok, ale u dat jsem hodně googlila, aby mi šla mezi sebou porovnávat a odečítat a teď si říkám, že mi tam zřejmě zbyly nějaké importy z nefunkčních řešení, tak si toho prosím nevšímej.

Mám jeden dotaz - models řádek 45 a 46 mám zakomentovanou fuknci, která by mi měla vrátit hezký formát u výpůjčky, ale nefunguje. Chtěla bych tam značku auta, protože nic jiného z výpůjčky se mi nehodí. Jenže v proměnné "auto" mám ForeignKey, předpokládám, že proto mi nefunguje? Dá se to nějak obejít prosím?

Děkuji a přeji hezký zbytek dne
Hedvika

**Comment by pesikj** [comment]
Ahoj Hedviko,

Pokud jde o metodu `___str___()`, tak ta musí vracet řetězec. Pokud chceš tedy vrátit nějaké pole (např. `ForeignKey`), musíš ho před vrácením pomocí `return` převést na řetězec ručně.

U těch datumů je potíž, že Django standardně využívá data včetně časových zón a ta nejdou s daty bez časových zón porovnat. Řešením je vypnutí časových zón nebo generování `now()` s využitím modulu `timezone` z Djanga, popsáno je to [zde](https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/).

### Příklad 46

Cizí klíče jsou správně, pouze nemusíš psát název třídy do uvozovek, pokud je vázaný model ve skriptu nad modelem, kde je cizí klíč.

### Příklad 47

Super, pouze na řádku 54 bych spíš použil operátor `and` namísto `&`. :-)

### Příklad 48

Super :-)

### Příklad 49

Super :-)

### Příklad 50

Taky super :-)

### Shrnutí

I se záludnými věcmi sis poradila, takže připisuji 5 bodů :-)
