### ISSUE TITLE
Hedvika - úkoly ze čtvrté lekce

### ISSUE THREAD

**Issue by Hedwika** [Hedwika/python-012021#4]
Ahoj Jirko,

posílám úkoly ze čtvrté lekce a prosím o kontrolu. Dělala jsem lehčí i těžší řešení, proto mám u většiny dvě verze, jen 20 posílám rovnou v těžší verzi, tam je to skoro stejné.

Děkuji a přeji hezkou neděli
Hedvika

**Comment by pesikj** [comment]
Ahoj Hedviko,

### Příklad 16

Super, líbí se mi volba Black Mirror :-)

### Příklad 17

Taky super, obě varianty, jen bych délku sledování před zobrazením zaokrouhlil :-)

### Příklad 18

Taky super :-)

### Příklad 19

Jsem moc rád, že jsi zvládla i pokročilou variantu :-)

### Příklad 20

Taky super 

### Shrnutí

Zvládla jsi to skvěle, zapisuji 5 bodů :-)
