### ISSUE TITLE
Úkoly z páté lekce

### ISSUE THREAD

**Issue by Hedwika** [Hedwika/python-012021#5]
Ahoj Jirko,

posílám ti úkoly z páté lekce a děkuji za kontrolu.

Hezký den
Hedvika

**Comment by pesikj** [comment]
Ahoj Hedviko,

### Příklad 21

Super :-)

### Příklad 22

Taky super, pouze poslední úkol sis mohla zjednodušit pomocí dvojtečky :-)

```python

gavin_gillam_books = character_deaths.loc["Gevin Harlaw": "Gillam", "GoT":"DwD"]

```

### Příklad 23

Taky super, líbí se mi názvy proměnných :-)

### Příklad 24

Taky super :-)

### Příklad 25

Taky super :-)

### Shrnutí

Máš vše perfektně zpracované včetně rozšíření a doplňků, takže připisuji 5 bodů :-)
