### ISSUE TITLE
Hedvika - úkoly z 6. lekce - agregace

### ISSUE THREAD

**Issue by Hedwika** [Hedwika/python-012021#6]
Ahoj Jirko,

posílám úkoly z šesté lekce a předem děkuji za kontrolu.

Příklad 27 - tady jsem si nebyla jistá u rozšířeného zadání: "proveď statistiku vykázaných hodin za jednotlivé kanceláře, tj. spočítej celkový počet hodin vykázaný zaměstnanci jednotlivých kanceláří na projekty daného zákazníka" - zda chceš vědět, kolik hodin vykázali v Liberci, Plzni a v Praze, nebo zda chceš vědět, kolik vykázali například v Praze na jednotlivých projektech. Dej mi prosím vědět, zda je to takto ok.

Příklad 30 - v rozšířeném zadání ve for cyklu jsem chtěla buňku vyplnit jako bunka.value = rozvrh_hodin[den][predmet], ale PyCharm mě nechtěl s indexy takto pustit. Tak jsem si vytvořila while cyklus, který je sice trochu delší, ale také myslím celkem OK. :) Pak jsem se tedy vrátila znovu k for cyklu a použila v něm místo indexu jiné proměnné než "predmet" a "den", které máme v cyklu. Tak nevím, zda mi něco neuniklo a nešlo by to udělat ve for cyklu snadněji, bez pomocných proměnných?

Děkuji a přeji hezký víkend
Hedvika

**Comment by pesikj** [comment]
Ahoj Hedviko,

### Příklad 26

Super

### Příklad 27

Původně jsem to myslel tak, že v tabulce budou vidět i projekty, tj. bude tam celkový počet hodin za kancelář a projekt, ale to je jen drobná změna (je to na řádku níže). Úkol upravovat nemusíš, ale můžeš se podívat, v jakém formátu je pak tabulka vypsaná, to má `pandas` docela promakané a vypadá to přehledně :-)

```python
hodiny_kancelare = zamestnanci_projekty.groupby(['město', "projekty"]).sum("hours")
```

### Příklad 28

Pokud tě zajímají jen některé sloupce, je zpravidla rychlejší vybrat ty sloupce podle dotazu, než z tabulky vyřazovat ty ostatní pomocí metody `drop()`.

Dále nemusíš přejmenovávat sloupec `name` na `count`. Pokud ti vadí, že je `name` v popisku, můžeš použít metodu `size()`, která vrátí jen počet řádků a tak nemá číslo název sloupce v záhlaví.

```python
print(subregiony_evropy.size())
```

Jinak super :-)

### Příklad 29

Super, pouze platí poznámka o metodě `drop()` :-)

### Příklad 30

Super, rozvrh máš moc hezky obarvený. :-)

V proměnné `predmet` máš přímo předmět, nikoli index a tím pádem stačí:

```python
bunka.value = predmet
```

Přičítám to tomu kurzu programování v C, kde bys na to šla přes ty indexy :-) Cyklus typu `while` by taky šel, případně i cyklus s využitím funkce `range()`.

A doporučil bych z těch několik oddělených podmínek vytvořit jednu, tj. kromě první podmínky namísto `if` použít `elif`. Fungovat to bude stejně, ale z pohledu výkonu bude ta druhá varianta rychlejší, protože část podmínek nebude potřeba vyhodnocovat.

### Shrnutí

Vše máš moc hezky zpracované a včetně bonusů, takže připisuji 5 bodů :-)

**Comment by Hedwika** [comment]
Ahoj Jirko,

děkuji moc za zprávu a za tipy! Já jsem si to stejně opravila, kdybych se k tomu potřebovala někdy vrátit, tak ať je to vše ok. Ráda bych tě poprosila, v případě budoucích podobných chybek, mohl bys mi jen napsat, co je špatně, ale už ne jak to vyřešit? :) Je to trochu sebemrskačské, ale ráda na to přijdu sama. Moc děkuji!

Příklad 30 - už to vidím, for je tady mnohem snazší a asi jsem ho trochu pozapomněla, jak to nepoužíváme. Nebo mi ho jen C přemazalo... :)

Děkuji
Hedvika

**Comment by pesikj** [comment]
Ahoj Hedviko,

není problém, bud jenom naznačovat :-D

Jirka
