### ISSUE TITLE
Hedvika: úkoly ze sedmé lekce

### ISSUE THREAD

**Issue by Hedwika** [Hedwika/python-012021#7]
Ahoj Jirko,

posílám úkoly ze sedmé lekce a předem děkuji za kontrolu.

Příklad 33 mám trochu jinak - rovnou jsem pracovala s názvy os a grafu, ale až pak jsem si přečetla dobrovolný doplněk a že jsi to chtěl jinak... :) Už jsem vše nechala s "fig", jak jsem měla, ale v příkladu 34 už používám "ax".

Děkuji a přeji hezký den
Hedvika

**Comment by pesikj** [comment]
Ahoj Hedviko,

### Příklad 31

Super :-)

### Příklad 32

Taky super :-)

### Příklad 33

Takto je to určitě v pohodě, to zadání je spíše doporučení, ale určitě není nutné to tak řešit :-)

### Příklad 34

Super (i bonus) :-)

### Příklad 35

Využíváš zbytečně `loc` na řádku 13, zkus to prosím napsat jako dotaz. Dále se ti zobrazují všechna data v jednom grafu, takže není možné porovnat města mezi sebou. Zkus se na to prosím ještě podívat, můžeš se inspirovat příkladem na sjezdovku, který jsme dělali na hodině - tj. vytvoř si novou tabulku, kde každé město bude mít svůj sloupec a z něj pak vytvoř krabicový graf.

### Shrnutí

Podívej se prosím ještě na příklad 35 (záměrně dle tvého přání pouze mírně napovídám), ostatní máš vyřešeno moc pěkně včetně bonusů, zatím připisuji 4 body :-)

**Comment by Hedwika** [comment]
Ahoj Jirko,

děkuji za opravu, já jsem si říkala, že nám ten graf nic moc neříká... :) Teď už je to lepší, snad je i postup ok.

Děkuji
Hedvika

**Comment by pesikj** [comment]
Ahoj Hedviko,

graf už vygenerovaný je, ale obsahuje data pouze za jeden den, nikoli za celý měsíc. Můžeš to prosím ještě upravit, abychom mohli porovnat teploty za celý listopad? :-)

Díky, Jirka

**Comment by Hedwika** [comment]
Ahoj Jirko,

děkuji za zprávu, s tímhle zadáním jsem se nějak minula pochopením :-D Tak snad už ti teď rozumím správně a je to v pořádku.

Děkuji
Hedvika
