### ISSUE TITLE
Hedvika: úkoly z deváté lekce

### ISSUE THREAD

**Issue by Hedwika** [Hedwika/python-012021#9]
Ahoj Jirko,

posílám úkoly z 9. lekce. Tentokrát bez problému a byl to asi nejrychlejší úkol vůbec. :)

Předem děkuji za opravu
Hedvika

**Comment by pesikj** [comment]
Ahoj Jirko,

### Příklad 41

Nastavení je správně :-)

### Příklad 42

Model je správně :-)

### Příklad 43

Super :-)

### Příklady 44 a 45

Též super

### Shrnutí

Tato sada asi byla jednoduchá, ale dobrá práce, připisuji 5 bodů :-)
